# https://github.com/crate-ci/typos/blob/master/docs/github-action.md

name: Spell Check with Typos
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Spell Check with Typos
        uses: crate-ci/typos@master
        with:
          config: ./.typos.toml
          write_changes: false # Set to report typos without making corrections
